# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""
# Title of the Site
title: Alps's Blog
# Description of the Site
description: Now You See Me
# URL of Image of the Site
# site-image: /WhatATheme/assets/images/meta.jpg
site-image: https://alps-images.obs.cn-east-2.myhuaweicloud.com/img/ITALIAN%20ALPS.jpg
# Keywords of the Site
site-keywords: Blog, Techs
# URL for the Image of custom Favicon
favicon-url: https://alps-images.obs.cn-east-2.myhuaweicloud.com/img/ITALIAN%20ALPS.jpg

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://alps-images.obs.cn-east-2.myhuaweicloud.com/img/thumb-1920-994659.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
bilibili_id: 510130968
email: 3270466046@qq.com
github_username: A1pss
csdn_id: m0_51900073
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: /
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: G-ZJ861TR7H7

# Disqus
disqus-shortname: Alps

# Name of the Author
author-name: Alps
# URL for the Image of the Author
author-image: https://alps-images.obs.cn-east-2.myhuaweicloud.com/img/QQ%E5%9B%BE%E7%89%8720210924081757.jpg
# 60 Words About the Author
author-about: Alps is Alpenliebe, Aspire to Become the World's No.1 Artificial Antelligence Expert
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/A1pss

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
